version: '3.1'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8087:8086"
    environment:
      - INFLUXDB_DB=my_metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_USER=my_user
      - INFLUXDB_USER_PASSWORD=my_password
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:


